version: '3.9'
services:
  postgres:
    profiles: ["test", "development"]
    image: postgres:14.5
    container_name: PostgreSQL
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: petdiary
      TZ: Asia/Seoul
    # volumes:
    #   - ${DOCKER_POSTGRES_VOLUME_PATH}
    ports:
      - 5432:5432
  
  redis:
    profiles: ["test", "development"]
    image: redis
    container_name: Redis
    restart: always
    ports:
      - 6379:6379